export const ErrorMessage = {
  invalidEmailOrPassword: 'Email or password is not valid',
  invalidEmail: 'User with this email does not exist',
  userExists: 'User already exists',
  invalidData: 'Invalid request data',
  pizzaExists: 'Pizza already exists',
  pizzaDoesntExist: 'Pizza does not exist',
  drinkExists: 'Drink already exists',
  drinkDoesntExist: 'Drink does not exist',
  saladExists: 'Salad already exists',
  saladDoesntExist: 'Salad does not exist',
  otherItemExists: 'Item of Other category already exists',
  otherItemDoesntExist: 'Item of Other category does not exist',
  invalidToken: 'Invalid token',
  noToken: 'Access denied. No token provided',
  notAdmin: 'Not an admin',
}