version: '3.8'
services:
  db:
    image: mongo:latest
    command: mongod --port ${MONGO_PORT}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - data:/var/lib/mongodb/data

  # backend:
  #   build: backend/.
  #   restart: always
  #   ports:
  #     - '${BACKEND_PORT}:${BACKEND_PORT}'
  #   depends_on:
  #     - db

  frontend:
    build: frontend/.
    restart: always
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    # depends_on:
    #   - backend

volumes:
  data: