version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/var/lib/mongodb/data

  backend:
    build: backend/.
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db

  frontend:
    build: frontend/.
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  data: